services:
  pgdatabase:
    image: postgres
    restart: always
    container_name: pgdatabase
    environment:
      - POSTGRES_USER=d2b_user
      - POSTGRES_PASSWORD=data2bots
      - POSTGRES_DB=data2bots
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U d2b_user -p data2bots" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: python3 load_data.py

